package nl.furusupport.basic;

enum DeviceState {
    ENDOFLIFEREACHED,
    LIFESPANPASSED,
    ADDED,
    OTHERREPAIRS,
    DUPLICATESERIAL,
    NEWSERIAL,
    DEVICE_NOT_IN_SYSTEM,
    UNKNOWN_ERROR,
    LIFEEXPECTANCYISOK,
    DEVICETEST_PASSED

}

enum DataState {
    IMPORT_SUCCEEDED,
    IMPORT_FAILED,
    DATABASE_NOT_EMPTY,
    DATAEXPORT_SUCCESFULL
}
